print ("Tugas Python")
print ()
nama = input("Masukan Nama Anda :")
panggilan = input("Masukan Panggilan :")
nim = input("Masukan NIM :")
tglhr = input("Masukan Tanggal Lahir :")
tmlhr = input("Masukan Tempat Lahir :")
tlpn = input("Masukan Nomor Telepon :")
alamat = input("Masukan Alamat :")
umur = input ("Masukan Umur Anda :")
print ()
print ("Assalamuallaikum")
print ()
print ("Let me introduce my self. my name is",nama,"but you can call me",panggilan,"My NIM is",nim,"I was born in",tmlhr,"and I am",umur,"years old. I am very gold if you want to invite my house in",alamat,". so,don't forget to call me before with the number",tlpn,)
print ()
print ("THANK YOU")
       
